### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by iamgabrielsoft** [codesplinta/busser#1]
I was unable to locate the package on npm, is it out of npm registry?

Or it's has been removed?

**Comment by codesplinta** [comment]
Hello @iamgabrielsoft . We are so sorry for the mix up. 

The **react_busser** is still in pre-alpha stage of development. It will be released to the public on the 27th of August, 2023.

Apologies once again

**Comment by iamgabrielsoft** [comment]
oh sounds good, just next month... 

has any app utilize the library so far during its current development phase?

**Comment by codesplinta** [comment]
Hello again @iamgabrielsoft 

No, there isn't any `ReactJS` web app that has made use of it so far during development however here is a DEMO of **busser** working:

https://codesandbox.io/s/react-busser-simple-demo-370ze6

**Comment by iamgabrielsoft** [comment]
have looked at the demo, are the states suppose to be reactive, since its uses event bus?

**Comment by codesplinta** [comment]
Hey @iamgabrielsoft , Sure, i welcome your ideas on how to improve it. However, i have to ask - In what area are you wishing to improve it ? Where do you think **busser** is lacking ?

Love to hear your thoughts

**Comment by iamgabrielsoft** [comment]
not really reactive, but event update. I think we can improve its event update by using methods like $on, $off, $update etc, just a simple reminder for developers.  I also notice its dependent on preact

**Comment by codesplinta** [comment]
Okay, got it. Also, the project is not really dependent on **preact** at all. The **preact** package is for making [*signals*](https://blog.logrocket.com/guide-better-state-managment-preact-signals/) available to the hooks inside the package.

**Comment by iamgabrielsoft** [comment]
Ok, have looked into the preact. State update needs to dependent on controlled state, not sure about the design, have used mobx and redux and I can say most state management lib till draws ideas from them

A first version needs to be release before contributing
