### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by iamgabrielsoft** [codesplinta/busser#4]
# Bug report

## Description / Observed Behavior
_package deprecation when installing react-busser_

This deprecation has to do with rollup-terser lib

What kind of issues did you encounter with busser?
![react-busser](https://github.com/codesplinta/busser/assets/71671874/9c2fc24d-1c06-45d2-98af-b63b776f8647)

## Expected Behavior
All packages used are expected to be compatible in subsequent release

## Additional Context

**busser**  latest release

**Comment by codesplinta** [comment]
Hello @iamgabrielsoft , You have to give us more details on the packages that were marked deprecated. 

There's very little to go on from the scanty details you provided here on this issue.

Please, make available more details with specific information on the packages you believe to be deprecated so this can be resolved sooner.

**Comment by codesplinta** [comment]
Thanks for the update @iamgabrielsoft , This will be fixed in the upcoming release v0.0.5.

**Comment by codesplinta** [comment]
Hello @iamgabrielsoft , v0.0.5 has now been released on NPM with the fix.

Thanks once again

**Comment by codesplinta** [comment]
Closing this out as this issue has been resolved!
